language: csharp  
mono: none
dotnet: 3.1
dist: trusty
sudo: false
solution: Amazon.DateTime.sln

script:
  - dotnet restore
  - dotnet build
  # - dotnet test tests/Amazon.DateTime.Tests/Amazon.DateTime.Tests.csproj
